//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbperobject
// {
//
//   float4x4 gWorldViewProj;           // Offset:    0 Size:    64 [unused]
//   float4x4 gWorldInvTranspose;       // Offset:   64 Size:    64 [unused]
//   float4x4 gWorld;                   // Offset:  128 Size:    64 [unused]
//   
//   struct Material
//   {
//       
//       float4 ambientColor;           // Offset:  192
//       float4 diffuseColor;           // Offset:  208
//       float4 specColor;              // Offset:  224
//
//   } material;                        // Offset:  192 Size:    48
//
// }
//
// cbuffer cbperframe
// {
//
//   struct DirectLight
//   {
//       
//       float4 ambientColor;           // Offset:    0
//       float4 diffuseColor;           // Offset:   16
//       float4 specColor;              // Offset:   32
//       float3 lightDir;               // Offset:   48
//       float pad;                     // Offset:   60
//
//   } dirLight;                        // Offset:    0 Size:    64
//   
//   struct PointLight
//   {
//       
//       float4 ambientColor;           // Offset:   64
//       float4 diffuseColor;           // Offset:   80
//       float4 specColor;              // Offset:   96
//       float3 position;               // Offset:  112
//       float range;                   // Offset:  124
//       float3 att;                    // Offset:  128
//       float pad;                     // Offset:  140
//
//   } pointLight;                      // Offset:   64 Size:    80 [unused]
//   
//   struct SpotLight
//   {
//       
//       float4 ambientColor;           // Offset:  144
//       float4 diffuseColor;           // Offset:  160
//       float4 specColor;              // Offset:  176
//       float3 position;               // Offset:  192
//       float range;                   // Offset:  204
//       float3 att;                    // Offset:  208
//       float pad;                     // Offset:  220
//       float3 lightDir;               // Offset:  224
//       float spotPower;               // Offset:  236
//
//   } spotLight;                       // Offset:  144 Size:    96 [unused]
//   float4 viewPosW;                   // Offset:  240 Size:    16
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbperobject                       cbuffer      NA          NA            cb0      1 
// cbperframe                        cbuffer      NA          NA            cb1      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// POSITION                 0   xyz         1     NONE   float   xyz 
// NORMAL                   0   xyz         2     NONE   float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[15], immediateIndexed
dcl_constantbuffer CB1[16], immediateIndexed
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_output o0.xyzw
dcl_temps 10
//
// Initial variable locations:
//   v0.x <- vout.PosH.x; v0.y <- vout.PosH.y; v0.z <- vout.PosH.z; v0.w <- vout.PosH.w; 
//   v1.x <- vout.PosW.x; v1.y <- vout.PosW.y; v1.z <- vout.PosW.z; 
//   v2.x <- vout.NormalW.x; v2.y <- vout.NormalW.y; v2.z <- vout.NormalW.z; 
//   o0.x <- <pixelShader return value>.x; o0.y <- <pixelShader return value>.y; o0.z <- <pixelShader return value>.z; o0.w <- <pixelShader return value>.w
//
#line 93 "D:\Programming\D3D11\D3D11\Box.hlsl"
mov r0.xyzw, l(0,0,0,0)  // r0.x <- color.x; r0.y <- color.y; r0.z <- color.z; r0.w <- color.w

#line 94
nop 
mov r1.xyzw, cb1[0].xyzw
mov r2.xyzw, cb1[1].xyzw
mov r3.xyzw, cb1[2].xyzw
mov r4.xyz, cb1[3].xyzx
mov r5.xyzw, cb0[12].xyzw
mov r6.xyzw, cb0[13].xyzw
mov r7.xyzw, cb0[14].xyzw
dp3 r4.w, v2.xyzx, v2.xyzx
rsq r4.w, r4.w
mul r8.xyz, r4.wwww, v2.xyzx
mov r9.xyz, v1.xyzx

#line 103
dp3 r4.w, r4.xyzx, r4.xyzx
rsq r4.w, r4.w
mul r4.xyz, r4.wwww, r4.xyzx  // r4.x <- lightDir.x; r4.y <- lightDir.y; r4.z <- lightDir.z

#line 104
mov r9.xyz, -r9.xyzx
add r9.xyz, r9.xyzx, cb1[15].xyzx
dp3 r4.w, r9.xyzx, r9.xyzx
rsq r4.w, r4.w
mul r9.xyz, r4.wwww, r9.xyzx  // r9.x <- viewDirW.x; r9.y <- viewDirW.y; r9.z <- viewDirW.z

#line 107
mul r1.xyzw, r1.xyzw, r5.xyzw  // r1.x <- ambient.x; r1.y <- ambient.y; r1.z <- ambient.z; r1.w <- ambient.w

#line 110
dp3 r4.w, r4.xyzx, r8.xyzx
itof r5.x, l(0)
max r4.w, r4.w, r5.x  // r4.w <- diffuseFactor

#line 113
ge r5.x, l(0.000000), r4.w
mov r5.y, l(0.400000)  // r5.y <- diffuseFactor

#line 114
lt r5.z, l(0.000000), r4.w
ge r4.w, l(0.500000), r4.w
and r4.w, r4.w, r5.z
if_nz r4.w
  mov r4.w, l(0.600000)  // r4.w <- diffuseFactor
else   // Prior locations: r5.y <- diffuseFactor

#line 115
  mov r4.w, l(1.000000)  // r4.w <- diffuseFactor
endif 
movc r4.w, r5.x, r5.y, r4.w

#line 117
mul r2.xyzw, r2.xyzw, r4.wwww
mul r2.xyzw, r6.xyzw, r2.xyzw  // r2.x <- diffuse.x; r2.y <- diffuse.y; r2.z <- diffuse.z; r2.w <- diffuse.w

#line 124
mov r4.xyz, -r4.xyzx
dp3 r4.w, r4.xyzx, r8.xyzx
add r4.w, r4.w, r4.w
mov r4.w, -r4.w
mul r5.xyz, r4.wwww, r8.xyzx
add r4.xyz, r4.xyzx, r5.xyzx  // r4.x <- reflectDir.x; r4.y <- reflectDir.y; r4.z <- reflectDir.z

#line 126
dp3 r4.x, r4.xyzx, r9.xyzx
itof r4.y, l(0)
max r4.x, r4.y, r4.x
log r4.x, r4.x
mul r4.x, r4.x, r7.w
exp r4.x, r4.x  // r4.x <- specFactor

#line 127
ge r4.y, l(0.100000), r4.x
ge r4.z, r4.x, l(0.000000)
and r4.y, r4.z, r4.y
if_nz r4.y
  mov r4.x, l(0)
else 

#line 128
  lt r4.y, l(0.100000), r4.x
  ge r4.z, l(0.800000), r4.x
  and r4.y, r4.z, r4.y
  if_nz r4.y
    mov r4.x, l(0.500000)
  else 

#line 129
    lt r4.y, l(0.800000), r4.x
    ge r4.z, l(1.000000), r4.x
    and r4.y, r4.z, r4.y
    if_nz r4.y
      mov r4.x, l(0.800000)
    endif 
  endif 
endif 

#line 131
mul r3.xyzw, r3.xyzw, r4.xxxx
mul r3.xyzw, r7.xyzw, r3.xyzw  // r3.x <- specular.x; r3.y <- specular.y; r3.z <- specular.z; r3.w <- specular.w

#line 134
add r1.xyzw, r1.xyzw, r2.xyzw
add r1.xyzw, r3.xyzw, r1.xyzw  // r1.x <- <calculateDirLight return value>.x; r1.y <- <calculateDirLight return value>.y; r1.z <- <calculateDirLight return value>.z; r1.w <- <calculateDirLight return value>.w

#line 94
add r0.xyzw, r0.xyzw, r1.xyzw

#line 97
mov o0.xyzw, r0.xyzw
ret 
// Approximately 77 instruction slots used
