//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
// Buffer Definitions: 
//
// cbuffer cbperobject
// {
//
//   float4x4 gWorldViewProj;           // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim      HLSL Bind  Count
// ------------------------------ ---------- ------- ----------- -------------- ------
// cbperobject                       cbuffer      NA          NA            cb0      1 
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// POSITION                 0   xyz         0     NONE   float   xyz 
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float   xyzw
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_constantbuffer CB0[4], immediateIndexed
dcl_input v0.xyz
dcl_input v1.xyzw
dcl_output_siv o0.xyzw, position
dcl_output o1.xyzw
dcl_temps 2
//
// Initial variable locations:
//   v0.x <- vin.iPosL.x; v0.y <- vin.iPosL.y; v0.z <- vin.iPosL.z; 
//   v1.x <- vin.iColor.x; v1.y <- vin.iColor.y; v1.z <- vin.iColor.z; v1.w <- vin.iColor.w; 
//   o1.x <- <vertexShader return value>.oColor.x; o1.y <- <vertexShader return value>.oColor.y; o1.z <- <vertexShader return value>.oColor.z; o1.w <- <vertexShader return value>.oColor.w; 
//   o0.x <- <vertexShader return value>.oPosH.x; o0.y <- <vertexShader return value>.oPosH.y; o0.z <- <vertexShader return value>.oPosH.z; o0.w <- <vertexShader return value>.oPosH.w
//
#line 21 "D:\Programming\D3D11\D3D11\Box.hlsl"
mov r0.xyz, v0.xyzx
mov r0.w, l(1.000000)
dp4 r1.x, r0.xyzw, cb0[0].xyzw  // r1.x <- vout.oPosH.x
dp4 r1.y, r0.xyzw, cb0[1].xyzw  // r1.y <- vout.oPosH.y
dp4 r1.z, r0.xyzw, cb0[2].xyzw  // r1.z <- vout.oPosH.z
dp4 r1.w, r0.xyzw, cb0[3].xyzw  // r1.w <- vout.oPosH.w

#line 22
mov r0.xyzw, v1.xyzw  // r0.x <- vout.oColor.x; r0.y <- vout.oColor.y; r0.z <- vout.oColor.z; r0.w <- vout.oColor.w

#line 24
mov o0.xyzw, r1.xyzw
mov o1.xyzw, r0.xyzw
ret 
// Approximately 10 instruction slots used
