//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_POSITION              0   xyzw        0      POS   float       
// COLOR                    0   xyzw        1     NONE   float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue  Format   Used
// -------------------- ----- ------ -------- -------- ------- ------
// SV_TARGET                0   xyzw        0   TARGET   float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed | skipOptimization
dcl_input_ps linear v1.xyzw
dcl_output o0.xyzw
//
// Initial variable locations:
//   v0.x <- vout.oPosH.x; v0.y <- vout.oPosH.y; v0.z <- vout.oPosH.z; v0.w <- vout.oPosH.w; 
//   v1.x <- vout.oColor.x; v1.y <- vout.oColor.y; v1.z <- vout.oColor.z; v1.w <- vout.oColor.w; 
//   o0.x <- <pixelShader return value>.x; o0.y <- <pixelShader return value>.y; o0.z <- <pixelShader return value>.z; o0.w <- <pixelShader return value>.w
//
#line 29 "D:\Programming\D3D11\D3D11\Box.hlsl"
mov o0.xyzw, v1.xyzw
ret 
// Approximately 2 instruction slots used
